export const TYPES = {
	CREATE_NOTE: 'CREATE_NOTE',
	DELETE_NOTE: 'DELETE_NOTE',
	SET_NOTES: 'SET_NOTES',
	PREPEND_NOTES: 'PREPEND_NOTES',
	APPEND_NOTES: 'APPEND_NOTES',
	CLEAR_IS_CREATED: 'CLEAR_IS_CREATED',
	SET_IS_DELETED: 'SET_IS_DELETED',
	SET_FILTER: 'SET_FILTER',
};
